import type { SchemaModule } from "../../db/migrate.ts";

/**
 * Verdicts in Postgres: what the user said about a film, and where it applies.
 *
 * The fifth schema module, alongside `oauth`, `web`, `taste` and `episodes`. Its
 * own module for the reason `episodes` is its own: a verdict is neither the taste
 * model nor history, and separate modules mean any of them can move without
 * renumbering the others.
 *
 * Nothing here references a genre, a mix, a movie row or an episode. A film is
 * named by title and year as text, exactly as an offer is in the episode schema,
 * because pointing a verdict at a Movie row would make saying *"I loved it"* a
 * way of editing the taste model. This table is the only place an opinion
 * lives: a Movie says the film is theirs and whether they watched it, and there
 * is nowhere on it to put what they thought.
 *
 * ## One table of acts, not two of verdicts and withdrawals
 *
 * The model calls both an **Act** and distinguishes them by `said`, because they
 * are the same kind of thing: something the user stated about a film at a time,
 * in a scope. Splitting them would mean ordering two tables against each other
 * to answer *"what stands"*, and the answer would depend on how the union was
 * built. One table keeps the order a property of the rows.
 *
 * ## Why the order acts arrived in is stored
 *
 * `said_at` is when the user spoke, to the millisecond, and it is the primary
 * order. Two tool calls can land in one millisecond, though, and then the
 * question *"which did they say second"* has to be answerable from something —
 * so `seq` records the order this table accepted them in. It is Postgres' to
 * allocate: no statement here supplies it, so nothing outside the database can
 * choose or forge one, and no two acts can share one.
 *
 * ## Why NULL means everywhere
 *
 *     occasion  text  NULL is the global scope. A value names one evening.
 *
 * §6: *"A Claim with no stated scope applies globally; one with a scope applies
 * **only** there."* The column is that sentence. It is deliberately not a text
 * column holding the word `everywhere`, which would make a typo into a private
 * scope nobody could see, and deliberately not a second boolean, which could
 * disagree with the occasion beside it.
 *
 * ## Why the constraints are here as well as in the model
 *
 * `lib/verdicts/model.ts` refuses a global *"not tonight"*, a scoped *"not
 * ever"*, an empty explanation and a withdrawal that asserts something. The
 * schema refuses them too. Not because the model is untrusted, but because a
 * table outlives the code that filled it: a later migration, a repair script or
 * a restore is a writer that never passed through a constructor, and the
 * invariant that matters most here — that an evening's refusal cannot become a
 * fact about the film — is one nobody should be able to write by hand either.
 */
export const VERDICTS_SCHEMA: SchemaModule = {
  module: "verdicts",
  migrations: [
    {
      version: 1,
      sql: `
        CREATE TABLE tonight_verdict_acts (
          user_id   text NOT NULL,
          -- Generated by Postgres, as everywhere else here. It identifies a row;
          -- it is never how the history is ordered — the model orders by the
          -- instant the user spoke, and this column is invisible to it.
          id        uuid NOT NULL DEFAULT gen_random_uuid(),

          -- A verdict, or the user taking one back.
          said      text NOT NULL,

          -- The film, named as a film is named. Not a foreign key: see above.
          title     text NOT NULL,
          year      integer NOT NULL,

          -- The scope. NULL is everywhere; a value is one evening.
          occasion  text,

          -- When they said it. The model canonicalises to UTC before it arrives.
          said_at   timestamptz NOT NULL,

          -- How it came to be said. NULL only for a withdrawal, which asserts
          -- nothing and so has no provenance of its own.
          told      text,

          -- What was asserted. All NULL for a withdrawal.
          about     text,
          judgement text,
          because   text,
          reach     text,
          reason    text,

          -- The user_id inside the key is what makes a cross-tenant reference
          -- inexpressible rather than merely unlikely, as in taste and episodes.
          PRIMARY KEY (user_id, id),
          UNIQUE (id),

          CONSTRAINT tonight_verdict_acts_said
            CHECK (said IN ('verdict', 'withdrawal')),
          CONSTRAINT tonight_verdict_acts_told
            CHECK (told IS NULL OR told IN ('volunteered', 'confirmed')),
          CONSTRAINT tonight_verdict_acts_about
            CHECK (about IS NULL OR about IN ('judgement', 'rejection')),
          CONSTRAINT tonight_verdict_acts_judgement
            CHECK (judgement IS NULL OR judgement IN ('liked', 'loved', 'disliked')),
          CONSTRAINT tonight_verdict_acts_reach
            CHECK (reach IS NULL OR reach IN ('not-tonight', 'not-ever')),

          -- Their words are their words, or they are absent. An empty string
          -- reads afterwards as something that was said and said nothing.
          CONSTRAINT tonight_verdict_acts_title CHECK (btrim(title) <> ''),
          CONSTRAINT tonight_verdict_acts_occasion
            CHECK (occasion IS NULL OR btrim(occasion) <> ''),
          CONSTRAINT tonight_verdict_acts_because
            CHECK (because IS NULL OR btrim(because) <> ''),
          CONSTRAINT tonight_verdict_acts_reason
            CHECK (reason IS NULL OR btrim(reason) <> ''),

          -- A withdrawal asserts nothing, so it carries none of the assertion.
          CONSTRAINT tonight_verdict_acts_withdrawal_asserts_nothing CHECK (
            said <> 'withdrawal' OR (
              told IS NULL AND about IS NULL AND judgement IS NULL
              AND because IS NULL AND reach IS NULL AND reason IS NULL
            )
          ),

          -- A verdict says who told it and what it is about, and carries exactly
          -- the fields of the one it is: a judgement has no reach, a rejection
          -- has no judgement, and neither holds the other's words.
          CONSTRAINT tonight_verdict_acts_verdict_asserts_something CHECK (
            said <> 'verdict' OR (
              told IS NOT NULL AND about IS NOT NULL AND (
                (about = 'judgement'
                  AND judgement IS NOT NULL AND reach IS NULL AND reason IS NULL)
                OR
                (about = 'rejection'
                  AND reach IS NOT NULL AND judgement IS NULL AND because IS NULL)
              )
            )
          ),

          -- The invariant this table exists to hold. "Not tonight" is about an
          -- evening and cannot be written without one; "not ever" and a
          -- judgement are about the film and cannot be written with one.
          CONSTRAINT tonight_verdict_acts_scope CHECK (
            said <> 'verdict' OR (
              CASE
                WHEN reach = 'not-tonight' THEN occasion IS NOT NULL
                ELSE occasion IS NULL
              END
            )
          )
        );

        -- One film's history, for one user, oldest first. The only read this
        -- slice makes, and the only index it needs.
        CREATE INDEX tonight_verdict_acts_film
          ON tonight_verdict_acts (user_id, title, year, said_at);
      `,
    },
    {
      // The order acts were accepted in, so that two claims made in the same
      // millisecond still resolve to the one the user said second.
      //
      // Appended rather than folded into v1, which has shipped. `said_at` has
      // millisecond resolution, and two tool calls can land inside one: without
      // this the model fell back to comparing content, which is deterministic
      // but is not "the later one wins" — a correction could silently not take.
      version: 2,
      sql: `
        -- Added without a default first, so rows written before this migration
        -- keep NULL. Backfilling them from a sequence would order them by
        -- however they happen to sit on disk, which is an invention rather than
        -- a fact: nothing recorded which of two same-instant legacy acts came
        -- first, and pretending otherwise is worse than admitting it.
        ALTER TABLE tonight_verdict_acts ADD COLUMN seq bigint;

        CREATE SEQUENCE tonight_verdict_acts_seq;

        -- Allocated by Postgres at insert. A sequence is atomic, shared by every
        -- connection and every process, and never hands the same number out
        -- twice — which is what makes this work across concurrent requests and
        -- across server instances, where a counter in the application could not.
        ALTER TABLE tonight_verdict_acts
          ALTER COLUMN seq SET DEFAULT nextval('tonight_verdict_acts_seq');

        -- Two acts sharing an order would leave the tie unbroken again. Unique
        -- rather than trusted: NULLs do not collide, so the legacy rows above
        -- are unaffected.
        CREATE UNIQUE INDEX tonight_verdict_acts_order
          ON tonight_verdict_acts (seq);
      `,
    },
  ],
};
