import type { SchemaModule } from "../../db/migrate.ts";

/**
 * Episodes in Postgres: an evening, and the films Tonight put forward in it.
 *
 * The fourth schema module, alongside `oauth`, `web` and `taste`. It is its own
 * module rather than a v5 of the taste schema because history is not taste, and
 * `lib/taste/store/schema.ts` said where it would go before it existed: "its own
 * migration and its own tables … evidence for *proposing* changes to this model
 * — never a second, invisible model that quietly outvotes it". Separate modules
 * also mean either can move without renumbering the other.
 *
 * Nothing here references a genre, a mix or a movie. An episode names the films
 * it offered as text, not as a foreign key into the taste model, because the two
 * are different claims: the taste model holds films the user told Tonight about,
 * and an offer holds a film Tonight mentioned once. Pointing one at the other
 * would make recommending a film a way of adding it to somebody's taste.
 *
 * ## Why NULL is the whole design
 *
 *     watched   boolean   NULL means nobody said. It does not mean no.
 *     finished  boolean   the same.
 *
 * `false` is something the user stated — *"I put it on and turned it off"* — and
 * `NULL` is silence. A column that could not tell them apart would turn every
 * unanswered evening into a stated negative, which is the fabricated-history
 * failure the architecture exists to prevent. Both are nullable and neither has
 * a default: a row is inserted with what is known and nothing is filled in.
 *
 * ## Why `chosen` sits on the offer and not on the episode
 *
 * "The film they chose is one of the films that were offered" is an invariant,
 * and the schema can either hold it or hope. A `chosen` column on the episode
 * would need a foreign key back into the offers table, which already points at
 * the episode — a cycle, and one that makes deleting an episode a puzzle.
 *
 * Marking the offer instead makes the invariant unsayable in the wrong way:
 * being chosen is a property of an offer, so there is no value that could name a
 * film Tonight never mentioned. The partial unique index below allows at most
 * one, and no chosen row at all is the unknown — which is exactly right, because
 * the model has no way to state "I chose nothing".
 */
export const EPISODES_SCHEMA: SchemaModule = {
  module: "episodes",
  migrations: [
    {
      version: 1,
      sql: `
        CREATE TABLE tonight_episodes (
          user_id     text NOT NULL,
          -- Generated by Postgres, for the same reason the taste model's ids are:
          -- one source of identity, and no application able to choose its own.
          id          uuid NOT NULL DEFAULT gen_random_uuid(),
          -- What they asked for, in their words. Never a paraphrase.
          request     text NOT NULL,

          -- The outcomes. Nullable on purpose, no default on purpose: see above.
          watched     boolean,
          finished    boolean,

          recorded_at timestamptz NOT NULL DEFAULT now(),

          -- The user_id inside the key is what makes a cross-tenant reference
          -- inexpressible rather than merely unlikely, exactly as in the taste
          -- schema. Two users may hold the same id and never see each other's.
          PRIMARY KEY (user_id, id),
          UNIQUE (id),

          CONSTRAINT tonight_episodes_request CHECK (btrim(request) <> '')
        );

        CREATE TABLE tonight_episode_offers (
          user_id  text NOT NULL,
          id       uuid NOT NULL DEFAULT gen_random_uuid(),
          episode  uuid NOT NULL,
          -- The order they were put in. An answer's directions are ordered by
          -- distance from the lead, and losing that would lose what was said.
          position integer NOT NULL,

          title    text NOT NULL,
          year     integer NOT NULL,
          -- Whether this was the lead or one of the directions.
          lead     boolean NOT NULL,
          -- Whether the user said they went with this one. Not nullable: the
          -- absence of a chosen row is the unknown, and a three-valued column
          -- here would invent a "they chose none" the model cannot express.
          chosen   boolean NOT NULL DEFAULT false,

          PRIMARY KEY (user_id, id),
          UNIQUE (id),
          UNIQUE (user_id, episode, position),

          -- An offer belonging to no episode is nothing, so it goes when the
          -- episode does.
          CONSTRAINT tonight_episode_offers_episode
            FOREIGN KEY (user_id, episode) REFERENCES tonight_episodes (user_id, id)
            ON DELETE CASCADE,

          CONSTRAINT tonight_episode_offers_title CHECK (btrim(title) <> '')
        );

        -- One lead per answer, and one film chosen per evening. Both are partial
        -- indexes because the constraint is on the true rows only: an evening may
        -- hold any number of offers that did not lead and were not chosen.
        CREATE UNIQUE INDEX tonight_episode_offers_lead
          ON tonight_episode_offers (user_id, episode) WHERE lead;
        CREATE UNIQUE INDEX tonight_episode_offers_chosen
          ON tonight_episode_offers (user_id, episode) WHERE chosen;
      `,
    },
  ],
};
