import type { SchemaModule } from "../../db/migrate.ts";

/**
 * Open questions in Postgres: which films are waiting on an answer.
 *
 * The sixth schema module, and its own rather than a second table inside
 * `verdicts`, because the two hold different kinds of thing. A verdict is the
 * user's claim; a question is Tonight's note to itself. Keeping them in separate
 * modules means a migration to one never touches the other, and — the reason
 * that matters — it makes "read this user's claims" a query that cannot return a
 * row nobody authored.
 *
 * ## What the table cannot hold
 *
 * There is no answer column, no guess, no confidence and no score. Adding any of
 * them would make an unanswered question into a weak opinion, which is the
 * failure §5 of the plan names: *"a question going unanswered across several
 * sessions is not a verdict either, and an unanswered question expires quietly
 * rather than hardening into an assumption."*
 *
 * `since` and `opportunities` are here because the approved retirement rule
 * needs both — 30 days, or three chances that went by. Neither is a measure of
 * anything: a question that ran out says nothing about the film and nothing
 * about the user, and retiring it is a removal rather than a conclusion. No
 * column exists for a conclusion to be written into.
 *
 * ## One question per film
 *
 * `UNIQUE (user_id, title, year)` — asking twice about the same film is the same
 * question, not two. The uniqueness is what makes `open` idempotent at the
 * storage level rather than by a read-then-write somebody could race, and it
 * keeps the first `since` rather than the latest: an old question must not be
 * able to look new.
 *
 * Nothing constrains how many films may be waiting at once. The plan sets no
 * such limit, and inventing one would decide something nobody decided.
 */
export const QUESTIONS_SCHEMA: SchemaModule = {
  module: "verdict_questions",
  migrations: [
    {
      version: 1,
      sql: `
        CREATE TABLE tonight_verdict_questions (
          user_id text NOT NULL,
          -- Generated by Postgres, as everywhere else here.
          id      uuid NOT NULL DEFAULT gen_random_uuid(),

          -- The film the question is about, named as a film is named. Not a
          -- foreign key into the taste model or into an episode: a question is
          -- about a film, and pointing it at a row would tie Tonight's note to
          -- somebody else's record of something.
          title   text NOT NULL,
          year    integer NOT NULL,

          -- When the question arose. Recorded, never interpreted.
          since   timestamptz NOT NULL,

          -- The user_id inside the key is what makes a cross-tenant reference
          -- inexpressible rather than merely unlikely, as in every module here.
          PRIMARY KEY (user_id, id),
          UNIQUE (id),

          -- Asking twice about one film is one question.
          UNIQUE (user_id, title, year),

          CONSTRAINT tonight_verdict_questions_title CHECK (btrim(title) <> '')
        );
      `,
    },
    {
      // The approved retirement rule needs one more fact than v1 recorded: how
      // many chances to ask have gone by. Appended rather than folded into v1,
      // which has shipped — a version already recorded is never re-run, so
      // editing it would leave two deployments disagreeing about the schema.
      version: 2,
      sql: `
        ALTER TABLE tonight_verdict_questions
          -- Counted only when a caller states that an eligible opportunity
          -- occurred. Never a measure of the user, and never incremented by a
          -- read: see \`opportunity\` in ../questions.ts.
          ADD COLUMN opportunities integer NOT NULL DEFAULT 0;

        -- Whole chances, from none. A negative count would be a number nobody
        -- could have reached, and the rule reads it as a threshold.
        ALTER TABLE tonight_verdict_questions
          ADD CONSTRAINT tonight_verdict_questions_opportunities
          CHECK (opportunities >= 0);
      `,
    },
  ],
};
